name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      fail-fast: false
      matrix:
        deno-version: ["v1.8", "v1.9", "canary"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@main
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Check all modules
      run: time deno cache **/*.ts

  publish:
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Upload modules

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno v1.9
      uses: denoland/setup-deno@main
      with:
        deno-version: v1.9

    - name: Publish to crux.land
      run: time ./tools/crux-publish@v1.ts . --update-readme

    - uses: EndBug/add-and-commit@v7
      with:
        add: README.md
        default_author: github_actions
        message: "Update crux.land URLs in README.md"
