name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:

  check:
    runs-on: ubuntu-latest
    name: Check w/ ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version:
        - v2.2
        - canary
      fail-fast: false # run each branch to completion

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Cache https://
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno/deps/https
        key: deno-https/v1-${{ github.sha }}
        restore-keys: deno-https/v1-

    - name: Check all modules
      run: time deno check --unstable **/*.ts

    - name: Ensure jsr.json is clean
      run: tools/update-jsr.ts

    - name: Check publish rules
      run: time deno publish --dry-run

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    name: Publish to JSR
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: denoland/setup-deno@v2

    - name: Cache https://
      uses: actions/cache@v4
      with:
        path: ~/.cache/deno/deps/https
        key: deno-https/v1-${{ github.sha }}
        restore-keys: deno-https/v1-

    - uses: actions/checkout@v4

    - name: Publish now
      run: deno publish
